### ISSUE TITLE
Sent Uri contains partially encoded path - version 2.2.2 (F-Droid)

### ISSUE THREAD

**Issue by billthefarmer** [openintents/filemanager#102]
Selecting a file sends a Uri containing a partially encoded path which confounds [Uri.getPath()](https://developer.android.com/reference/android/net/Uri.html#getPath()) and [Uri.getPathSegments()](https://developer.android.com/reference/android/net/Uri.html#getPathSegments()), possibly related to #38. Using the file manager as a picker seems to work normally. This is the content of the intent sent captured by Intent Intercept.
```shell
intent://org.openintents.filemanager/%2Fstorage%2Femulated%2F0%2FTest.txt#Intent;scheme=content;type=text/plain;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://org.openintents.filemanager/%2Fstorage%2Femulated%2F0%2FTest.txt 
MIME: text/plain 
URI: intent://org.openintents.filemanager/%2Fstorage%2Femulated%2F0%2FTest.txt#Intent;scheme=content;type=text/plain;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
```
This is the output of Uri.getPath() and Uri.getPathSegments() with Uri sent from the file manager.
```shell
Path: //storage/emulated/0/Test.txt
Segments: [/storage/emulated/0/Test.txt]
```
Using the file picker.
```shell
Path: /storage/emulated/0/Test.txt
Segments: [storage, emulated, 0, Test.txt]
```

**Comment by jagaarya16** [comment]
Namaste

**Comment by jagaarya16** [comment]
Nice

**Comment by jagaarya16** [comment]
Please update

**Comment by friedger** [comment]
This is the intended behavior, not sure what the issue is for you? Which file picker are you using? You shouldn't try to understand the data uris from other apps.

**Comment by billthefarmer** [comment]
I don't think you have understood the issue. The issue is that the Uri sent by the file manager contains a mixture of escaped and unescaped path separator characters, including two together, one escaped and one not. Of course this may have been fixed since I raised the issue, I haven't checked.

**Comment by friedger** [comment]
the segments should indeed be just what you mentioned in your issue:
`Segments: [/storage/emulated/0/Test.txt]`
