### ISSUE TITLE
Create Folder At ExtSdCard is Not Work || Oi File Manager Application

### ISSUE THREAD

**Issue by fadligenta** [openintents/filemanager#111]
#### Expected behavior<br>
<br>
Hope when adding new Folders can work.<br>
<br>
#### Actual behavior<br>
<br>
Can not add new Folder on SD CARD. And always appear &quot;Could not create directory&quot;<br>
<br>
#### How to reproduce<br>
<br>
* Download the Oi File Manager app on playstore Or [Here](https://play.google.com/store/apps/details?id=org.openintents.filemanager)
* Launch App<br>
* Click on &quot;Storage&quot;<br>
* Then Click &quot;extSdCard&quot;<br>
* Click on the icon in the upper right corner.<br>
* Click &quot;Create Folder&quot; at the bottom.<br>
<br>
- Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
<br>
* Application version: 2.2.2<br>
<br>

#### Recording Of The Bug
https://youtu.be/bedoD2WR150<br>
<br>
<br>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fadligenta/create-folder-at-extsdcard-is-not-work-or-or-oi-file-manager-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by friedger** [comment]
Could you please verify the permissions?
