### ISSUE TITLE
Bug found in OI File Manager ( when i use Bluetooth option  The app is stopped   )

### ISSUE THREAD

**Issue by abdulmalikkhan655** [openintents/filemanager#113]
#### Expected behavior
according to my information  When I want to send a document to another device simply select the file and select Bluetooth option  document or media should be   send to another device where you want to send 

#### Actual behavior
The application stops when I send  any document or video in other mobile through Bluetooth

#### How to reproduce
* [download ](https://f-droid.org/packages/org.openintents.filemanager/)and open the application 
* Select the files you want to send 
*   click on 3 vertical dots 
*  then click the more option
* select the bluetooth
* note bug 
* Browser: OI File Manager version  2.2.2
* Operating system:android 7.0
* smart phone Qmobile E2 noir

#### Recording Of The Bug
https://youtu.be/5zmViz_wNhk

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/bug-found-in-oi-file-manager-when-i-use-bluetooth-option-the-app-is-stopped">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by friedger** [comment]
This looks like an issue of the Bluetooth share app and how it handles intents received from other apps.
