### ISSUE TITLE
Bug Found in Ol File Manager (  When i click on copy and past option The screen is black )

### ISSUE THREAD

**Issue by abdulmalikkhan655** [openintents/filemanager#114]
#### Expected behavior
according to knowledge when we use copy  and past option  Another copy of the picture should be in  same directory 

#### Actual behavior
when i click on the copy past option  The screen turns black you can see in the bug video And no function shows

#### How to reproduce
* [download ](https://f-droid.org/packages/org.openintents.filemanager/)and open the application
* select the any image 
* click on 3 vertical dots
* then click the more option
* select copy and past option
*  note bug 
* Browser: OI File Manager version 2.2.2
* Operating system:android 7.0
* smart phone Qmobile E2 noir

#### Recording Of The Bug
https://youtu.be/QimXCS7MPds
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/bug-found-in-ol-file-manager-when-i-click-on-copy-and-past-option-the-screen-is-black">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by onozasi** [comment]
https://cdn.discordapp.com/attachments/377196081408376832/431044837954027530/IMG_20180404_115744_213.jpg
The app seems to have duplicate function as well. Each time the first copy and paste is been clicked on, it goes blank as mentioned by @abdulmalikkhan655, also, each time the second or third copy/past function is clicked on, the app crashes or gives an error report saying **Gallery has stopped**... i think this needs to be looked into asap.... most of the functions are just too buggy :P

**Comment by veniosg** [comment]
@onozasi Access to your screenshot is denied. 
@onozasi @abdulmalikkhan655 None of the options inside "More" are coming from OI File Manager. They are actions exposed by other apps you have installed, so you should report this to whichever app is exposing it (in @onozasi 's case it's probably "Gallery" as the error suggests). I know this is far from obvious and could be something to improve on, but that's a different discussion altogether.
