### ISSUE TITLE
OI File Manager: App crashes when clicked on "picture"

### ISSUE THREAD

**Issue by Godwyyn** [openintents/filemanager#115]
#### Expected behavior
When I highlight a folder in the storage,click on the menu icon and select picture from the drop down menu,I expected the app to display pictures or show pictures in the selected folder successfully without crashing.

#### Actual behavior
When I highlight a folder, and click on "picture" from the drop down menu options, the app crashes and exit.

#### How to reproduce
- Download the OI File Manager from Playstore
- Launch the app
- At the Home Activity,from the list of Folders
- Click and hold to highlight a folder
- Click on the menu icon
- From the drop down options, Click on "picture"
- App Crashes and Exit.

* Version: Version 2.2.2 
* Operating system: Infinix Hot, Android 4.4.2(Kitkat)

#### Recording Of The Bug
https://www.youtube.com/watch?v=Qozzhpce6AE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/oi-file-manager-app-crashes-when-clicked-on-picture">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by friedger** [comment]
This looks like an issue of the gallery app and how it handles intents received from other apps.
