### ISSUE TITLE
Browser not shown in 'Open With'

### ISSUE THREAD

**Issue by VersloB** [openintents/filemanager#116]
Adroid 6,0,1 with OI 2,2,2 and Firefox 59,0,2 installed.
When attempting to open an .svg file no browser is offered in 'Open With' nor can a find a way to remove/add a file association for .svg - Firefox is set as the default browser. Installing either 'SVG redirect' or 'SVG Viewer'  does not resolve the issue.

**Comment by friedger** [comment]
svg mime type support has been added. Could you please try beta version 2.2.3 at https://play.google.com/apps/testing/org.openintents.filemanager
