### ISSUE TITLE
2.3.1 not working with Android 10

### ISSUE THREAD

**Issue by genesis0x0** [openintents/filemanager#136]
App no longer works after Android 10 update. Shows message:
An error occurred:no access

**Comment by friedger** [comment]
This is a problem with Android 10, please contact Google ;-)

I will see what we can do, however, I am pessimistic. Android is trying to protect their users and force them to use system file managers.

For reference: https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

**Comment by friedger** [comment]
Duplicate to #134
