### ISSUE TITLE
Selecting a file and pressing cut displays a distorted error message

### ISSUE THREAD

**Issue by nfarmer** [openintents/filemanager#43]
When I select a file and press the "cut" button  it displays a distorted error message: 

> [indecipherable text] to move

Pasting the file still works though.

I'm running OI File Manager 2.0.5 on a Nook HD+ (software ver 2.2.0).

The previous version (I'm set to auto-update) didn't have this behavior.

![screenshot_2014-02-19-22-56-06](https://f.cloud.github.com/assets/2955449/2214986/5423d24e-99e3-11e3-8fc7-37d56b2b7d08.png)

P.S. Thank you for making OI File Manager; this bug reminded me of how extensively I use it.

**Comment by friedger** [comment]
fixed by a18f63213a0bbc7b92e1d4745d1ae5777a273e57
