### ISSUE TITLE
Doubled Fields in string.xml-Files

### ISSUE THREAD

**Issue by wirthual** [openintents/filemanager#44]
Hello everybody,

i just checked out your code and i got errors in almoste every string.xml that there are doubled value names. Maybe there wend something wrong. 

The doubled fields are:
 
menu_send
menu_delete
menu_move
menu_copy
menu_compress
menu_rename
menu_extract
menu_details

Hope this helps. 

Btw, Great work :+1:

**Comment by friedger** [comment]
fixed by https://github.com/openintents/filemanager/commit/2f5e8c8ab926da94aaedfdc45f155d6601b621d0
