### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by ghost** [openintents/filemanager#47]
Issue: OI File Manager interface language is in English (2.0.5 version) despite that the android device (Android version 4.1.2) interface language is Ukrainian.

Expected behaviour: OI File Manager interface is expected to be Ukrainian. The respective launchpad translation project is shown as finished in 2012 (https://translations.launchpad.net/openintents/trunk/+lang/uk).

Way to recreate: Change an android device interface language to Ukrainian. Open OI File Manager.

**Comment by friedger** [comment]
fixed in https://github.com/openintents/filemanager/commit/fa9ef2ab24b2f0e272af7f19bcad8d4a93ea5673
