### ISSUE TITLE
latest code cannot be built

### ISSUE THREAD

**Issue by haobug** [openintents/filemanager#53]
$ cd FileManager
$ ant debug 
Buildfile: /path/to/src/filemanager/FileManager/build.xml

BUILD FAILED
/path/to/src/filemanager/FileManager/build.xml:35: Cannot find /path/to/src/distribution/ant/build_common.xml imported from /path/to/src/filemanager/FileManager/build.xml

Total time: 0 seconds

**Comment by haobug** [comment]
have cloned that distribution repo, but failed to build still
$ ant debug
/opt/android-sdk-linux/tools/ant/build.xml:573: com.android.io.StreamException: java.io.FileNotFoundException: /path/to/src/distribution/DistributionLibrary/AndroidManifest.xml

@friedger

**Comment by friedger** [comment]
We have changed to gradle build by now. Could you please try that?

**Comment by haobug** [comment]
@friedger the DistributionLibrary can be built with `sh gradlew assembleRelease`,
but the Filemanager is the ant project,  ant requires the DistributionLibrary to meet the ant rules some how.  i have tried to do some hacks, but have not got the working solution since i am new to ant building.

**Comment by friedger** [comment]
@haobug you are right. Let's move Filemanager to gradle as well. I have time over the weekend.

**Comment by haobug** [comment]
@friedger did you feel that the gradle builds slower than ant? i prefer ant over gradle actually. 
so please keep the ant support files if it does not break the gradle build.
i am working on hacks of ant xmls.

**Comment by haobug** [comment]
build SUCCESSFUL

it looks the android sdk has a bug, they hardcoded the AndroidManifest.xml path. it must be at the root of  Android project. 
this link also gives the workaround: copy the same AndroidManifest.xml to project root(i created sym-link instead).
http://stackoverflow.com/questions/12411419/how-to-specify-path-of-androidmanifest-xml-file-in-gettype-ant-target

**Comment by haobug** [comment]
the can be built now,
but the FileManager project has another build issue:
/path/to/src/filemanager/FileManager/res/xml/about.xml:10: error: Error: No resource found that matches the given name (at 'resource' with value '@raw/license_short').

**Comment by friedger** [comment]
Fixed
