### ISSUE TITLE
Add support for blind people

### ISSUE THREAD

**Issue by Axxiss** [openintents/filemanager#54]
Blind people definitely have a bad time when it comes to using an app without text to speech feature. 

It could be possible to add this?

I was thinking of the following:

1. use volume up/down to navigate through each item inside a folder
2. each time an item is selected read the name aloud
3. open an item by a double tap or perhaps using power button

What do you think?

I'm interested on sending a PR a soon as i have something usable.
PS: the idea come from this reddit [thread][1]

[1]: http://www.reddit.com/r/androiddev/comments/30hzve/hey_randroiddev_what_is_the_least_amount_of/

**Comment by friedger** [comment]
Definitely! Thanks for pointing out again. 

Let's start a branch..

**Comment by aperomsik** [comment]
I haven't tried it... doesn't OIFM work with Android's built-in accessibility support?

(For what it's worth, my father in law is blind, but he uses an iphone so this won't help him.)

**Comment by Axxiss** [comment]
Well, I have done some research, OIFM works perfectly with talkback, so there is no need to reinvent the weel. I'm closing this.
