### ISSUE TITLE
"Couldn't create folder" on extSdCard on Samsung Galaxy S5 Android 5.0

### ISSUE THREAD

**Issue by asd-and-Rizzo** [openintents/filemanager#55]
1. Go into folder on external card
2. Create new folder

Expected: folder created

Actual: error with message "Couldn't create folder"

Notes: 
1. Build in "My Files" file manager created folder in same situation
2. File Manager Pro failed to create folder either
3. Card is visible under "storage/extSdCard" name
4. Folder is created well on build in memory card
5. SD card worked well on other phones with Androids 4.X

**Comment by friedger** [comment]
Android 5.0 has read-only access on secondary storage devices. Only system apps can received write access on these storage devices.

**Comment by asd-and-Rizzo** [comment]
Will rooting device and elevating fm help? Or other  simpler method? Anyway message with more meaningfull will be helpfull?

**Comment by friedger** [comment]
There is a discussion how to get around that partly by using the storage acesss framework. See e.g. http://stackoverflow.com/questions/22706484/does-safstorage-access-framework-solve-the-sd-card-write-issue-in-android-4-4

With root everything is possible, e.g. through native i/o calls.

I have updated the comment https://github.com/openintents/filemanager/issues/55#issuecomment-214386846 to make it more clear.

**Comment by friedger** [comment]
@asd-and-Rizzo Feel free to join for a chat at https://gitter.im/openintents/filemanager
