### ISSUE TITLE
Question: Settings?

### ISSUE THREAD

**Issue by Geyup** [openintents/filemanager#73]
Hello,

Great file manager, I hope this will always stay small and light weight!

I noticed on GooglePlay it shows it with a light colored theme, but I don't see any settings?

Are there suppose to be settings/preferences?

thanks

**Comment by friedger** [comment]
There is the overflow menu that contains settings. In there, you should find a menu "Use dark theme".

**Comment by Geyup** [comment]
I checked on the top, bottom sides, tried to swipe, left, right, up down, looked everywhere, nothing here....

Turns out I didn't really like the file manager, and I deleted it...

Thanks though...
