### ISSUE TITLE
Add MIME Types for Book Formats

### ISSUE THREAD

**Issue by iampradip** [openintents/filemanager#75]
Some book files are not opening with "Application not available" toast even though they have correct file extension. Adding following lines have solved the problem:

`/res/xml/mimetypes.xml`

	
	<type extension=".epub" mimetype="application/epub+zip" icon="@drawable/ic_launcher_text_plain" />
	<type extension=".chm" mimetype="application/vnd.ms-htmlhelp" icon="@drawable/ic_launcher_text_plain" />
	<type extension=".pdf" mimetype="application/pdf" icon="@drawable/ic_launcher_text_plain" />
	<type extension=".mobi" mimetype="application/x-mobipocket-ebook" icon="@drawable/ic_launcher_text_plain" />

I don't like the icons but I didn't see any other icons fit for books. Please add these lines for release.

**Comment by friedger** [comment]
Will be included in the next version (fixed by e49c6bd309eafb1a8a99c0baf84271269005a109)
