### ISSUE TITLE
Moving files within the SD card failed

### ISSUE THREAD

**Issue by dandv** [openintents/filemanager#80]
1. Navigate to a file on the SD card, under `/storage/XXXX-XXXX/DCIM/Camera`
2. Cut the file
3. Navigate on the (same) SD card to `/storage/XXXX-XXXX/Photos/Google
4. Paste the file

["Moving..." takes a while, even though the file is on the same filesystem.](http://stackoverflow.com/questions/38445352/why-is-moving-images-in-android-gallery-apps-so-slow)

After a few seconds, an error toast pops up: `Some or all items couldn't be moved!`

Samsung GS7, not rooted.

**Comment by friedger** [comment]
Needs more details.
