### ISSUE TITLE
CompressManager creates zip files of size 0 Bytes

### ISSUE THREAD

**Issue by jordantrain** [openintents/filemanager#85]
After downloading the zipped project, unzipping it and importing it into Android Studio, I encountered this problem:
For a file that is not a directory, CompressManager creates 0 Byte zip files.  Numerous file types (txt, xml, html) were tested all yielding same 0 Byte results.  Yes, the original files were more than 0 bytes.

**Comment by friedger** [comment]
Could be related to missing write permissions. Could you please verify whether you can copy the file in that folder?

**Comment by friedger** [comment]
needs more details.
