### ISSUE TITLE
Strange behaviour of version 2.20 from F-Droid - settings crash and no access to files

### ISSUE THREAD

**Issue by billthefarmer** [openintents/filemanager#91]
I upgraded from version 2.05 which works fine.

I have two different devices running LineageOS 14.1 - android 7.1.2. On the Nexus 7 running an unofficial build the file manager can't access the main public folder - storage/emulated/0 in this case. The error reported on the storage/emulated folder display is 'An error occurred:no access'. The settings work fine.

On the Moto G running an official nightly build the file manager works fine, including sending files to other apps, but the first time I tried the settings I got the standard 'Unfortunately OI File Manager has stopped' message, on further attempts the app just disappears from the screen. There doesn't seem to be anything useful in the log, I have included everything in case it is helpful:
```
10-24 13:35:39.582   667  1037 I ActivityManager: Process org.openintents.filemanager (pid 13484) has died
10-24 13:35:39.582   667  1037 D ActivityManager: cleanUpApplicationRecord -- 13484
10-24 13:35:39.583   667  1825 I WindowManager: WIN DEATH: Window{43c68a8 u0 org.openintents.filemanager/org.openintents.filemanager.FileManagerActivity}
10-24 13:35:39.583   667  1825 W WindowManager: Force-removing child win Window{867d7bb u0 PopupWindow:c61d8af EXITING} from container Window{43c68a8 u0 org.openintents.filemanager/org.openintents.filemanager.FileManagerActivity}
10-24 13:35:39.588   667   686 I WindowManager: WIN DEATH: Window{3e296f0 u0 org.openintents.filemanager/org.openintents.filemanager.PreferenceActivity}
10-24 13:35:39.608  2709  2709 I Finsky  : [1] com.google.android.finsky.bn.a.onTrimMemory(5): Memory trim requested to level 5
10-24 13:35:39.614  3532  3532 D GeckoMemoryMonitor: onTrimMemory() notification received with level 5
10-24 13:35:39.614  3532  3532 D GeckoMemoryMonitor: increasing memory pressure to 2
10-24 13:35:39.623   667  6460 I OpenGLRenderer: Initialized EGL, version 1.4
10-24 13:35:39.623   667  6460 D OpenGLRenderer: Swap behavior 1
10-24 13:35:39.649   667   697 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-24 13:35:39.667  3414 18930 I Error   : 408 Request Time-out: Read timed out
10-24 13:35:39.675   667  1802 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{f547668 0:org.openintents.filemanager/u0a143}
```

**Comment by friedger** [comment]
@billthefarmer for issue on Nexus 7, could you please verify that it is indeed storage/emulated/0 that give the error? Could you please also verify that the app has permission to read/write the storage?

For the Moto G issue with settings, a fix has been committed. Thanks for reporting. It should be included in 2.2.1.

**Comment by billthefarmer** [comment]
Here's what's on the screen...
![screenshot_20171024-144341](https://user-images.githubusercontent.com/3448386/31946994-3fc898a6-b8cb-11e7-8964-f0a7e8723a92.png)
The permissions are a bit odd, but it's the same on the Moto G and that works...
```shell
Bill@Cynthia MINGW64 ~
$ /d/adt/android-sdk-windows/platform-tools/adb shell ls -al storage
total 8
drwxr-xr-x  4 root root        80 2017-10-24 08:18 .
drwxr-xr-x 17 root root         0 2017-10-24 08:18 ..
drwx--x--x  6 root sdcard_rw 4096 2016-09-19 10:24 emulated
drwxr-xr-x  2 root root        60 2017-10-24 08:17 self

Bill@Cynthia MINGW64 ~
$ /d/adt/android-sdk-windows/platform-tools/adb shell ls -al storage/emulated
ls: storage/emulated: Permission denied

Bill@Cynthia MINGW64 ~
$ /d/adt/android-sdk-windows/platform-tools/adb shell ls -al storage/emulated/0
total 244
drwxrwx--x 36 root sdcard_rw  4096 2017-10-21 09:12 .
drwx--x--x  6 root sdcard_rw  4096 2016-09-19 10:24 ..
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 .adobe-digital-editions
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 .eBooksparam
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 Alarms
drwxrwx--x  4 root sdcard_rw  4096 2016-10-24 17:46 Android
drwxrwx--x  2 root sdcard_rw  4096 2017-05-24 09:25 Audio Recorder
drwxrwx--x  6 root sdcard_rw  4096 2017-10-04 20:03 DCIM
drwxrwx--x  3 root sdcard_rw  4096 2016-10-24 17:46 DevexpertNET
drwxrwx--x  6 root sdcard_rw  4096 2017-06-12 17:17 Diary
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 Digital Editions
drwxrwx--x  2 root sdcard_rw  4096 2017-10-13 18:14 Documents
drwxrwx--x 35 root sdcard_rw 16384 2017-10-19 21:17 Download
-rw-rw----  1 root sdcard_rw   327 2017-10-19 09:10 Editor.text
drwxrwx--x  2 root sdcard_rw  4096 2017-02-12 15:31 FloatingStickies
drwxrwx--x  2 root sdcard_rw  4096 2017-04-12 14:54 MLManager
drwxrwx--x  5 root sdcard_rw  4096 2017-10-20 18:28 MapsWithMe
drwxrwx--x  2 root sdcard_rw  4096 2017-09-29 11:56 Movies
drwxrwx--x  2 root sdcard_rw  4096 2017-09-29 11:38 Music
drwxrwx--x  8 root sdcard_rw  4096 2016-11-01 10:24 Navigon
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 Notifications
drwxrwx--x  2 root sdcard_rw  4096 2017-07-07 17:37 Open-GApps
drwxrwx--x  2 root sdcard_rw  4096 2017-10-06 14:27 OpenAPK
drwxrwx--x  2 root sdcard_rw  4096 2016-10-30 15:00 OpenVPN
drwxrwx--x  3 root sdcard_rw  4096 2016-12-02 09:42 Pictures
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 Podcasts
drwxrwx--x  2 root sdcard_rw  4096 2016-10-24 17:46 Ringtones
drwxrwx--x  2 root sdcard_rw  4096 2017-09-20 12:06 Shorty
drwxrwx--x  3 root sdcard_rw  4096 2017-07-03 08:37 TWRP
drwxrwx--x  6 root sdcard_rw  4096 2017-10-07 19:03 Tencent
drwxrwx--x  2 root sdcard_rw  4096 2017-07-02 20:00 bluetooth
drwxrwx--x  3 root sdcard_rw  4096 2017-06-17 21:13 cocoafish
drwxrwx--x 16 root sdcard_rw  4096 2017-10-23 21:58 eBooks
drwxrwx--x  2 root sdcard_rw  4096 2017-06-24 15:03 easy xkcd
drwxrwx--x  3 root sdcard_rw  4096 2017-07-03 12:55 osmdroid
drwxrwx--x  2 root sdcard_rw  4096 2017-07-04 22:17 storage
drwxrwx--x  3 root sdcard_rw  4096 2017-10-05 08:53 tbs
```

**Comment by friedger** [comment]
And can you verify the permissions of OI Filemanager?

**Comment by billthefarmer** [comment]
I don't know how to do that

**Comment by friedger** [comment]
@billthefarmer Please have a look in the Android settings -> Apps -> OI Filemanager -> permissions. Storage should be enabled.

**Comment by billthefarmer** [comment]
Yes, it has storage permission, it was asked for when I first started the app. If I take it away it gets asked for again.

**Comment by friedger** [comment]
@billthefarmer And 2.0.5 didn't have the issue with the Nexus 7? Strange.

**Comment by billthefarmer** [comment]
This is version 2.07 I just installed from the Play Store...
![screenshot_20171024-203932](https://user-images.githubusercontent.com/3448386/31964381-c1326590-b8fb-11e7-954f-8398bd79e54f.png)
As you can see, it works.

**Comment by friedger** [comment]
@billthefarmer In, 2.2.0, if you click on "0", I assume you see the same thing again. The mechanism to read directories has not changed. It needs further investigation. If you have any more pointers about what you observed that would be great.

**Comment by billthefarmer** [comment]
Yes, it did. I reinstalled version 2.2.0 from F-Droid on the Nexus 7 and checked it again, which was the same as before. I then tried the OI File Manager file picker from another app, and that worked OK, including selecting and loading a file. I then tried the file manager again and it worked fine, as it should, including sending a file to another app. I have rebooted the device, and it still works fine, so it seems to have fixed itself. If I select the home (/) button and then storage, and then emulated I get the error back, but selecting 0 works.

**Comment by friedger** [comment]
Glad to see that it worked. Still strange though that it was not working before.

The error when clicking on "emulated" is happening usually on all devices because the operating system (Android) does not allow to read these files. 

I will close this issue. Feel free to open a new one if you have more suggestions or issues.

**Comment by b4198eb1aa** [comment]
Awesome app! I love it. Not sure where to suggest a new feature other than this "issues" list.  I did look but could not find a more appropriate place.

Shorty has one list of stations.  It would be great if could support multiple lists. For example, a list of different user categories such as format, country, language. 

I have developed my own system where each Shorty "Station name" is preceeded by a three digit code and my list is sorted alphabetically. Here is one entry as an example:

ma8 CILV 88.5 FM Ottawa, ON

the first digit of m means MUSIC
the second digit a means ADVERTS or commercials (unlike noncommercial stations such as the BBC)
the third digit is my measurement of how fast the stream loads - 8 is the fastest, 1 is the slowest.

Of course, other uses would have their own categories. 

Thank you again for a wonderful app!

**Comment by billthefarmer** [comment]
@b4198eb1aa I don't know how you managed to get here. The issues page for [Shorty](https://github.com/billthefarmer/shorty) is [here](https://github.com/billthefarmer/shorty/issues). I have copied this to [here]().

@openintents please ignore this.

**Comment by jormer1043** [comment]
> Esto es lo que hay en la pantalla ... Los permisos son un poco extraños, pero es lo mismo en el Moto G y eso funciona ...
> ![screenshot_20171024-144341](https://user-images.githubusercontent.com/3448386/31946994-3fc898a6-b8cb-11e7-8964-f0a7e8723a92.png)
> 



Buenas tardes.

Sé que ha pasado tiempo, pero he adquirido un Smartphone nuevo con Android 10 y me sale justamente el error de no acceso.
Verfifiqué los permisos pero aún así me sigue arrojando el error, en cambio en una tableta que maneja Android 7.0 funciona correctamente. Ya he reinstalado varias veces la aplicación OI File Manager sin ningún éxito, agradezco la ayuda, ya que usar otro móvil no es opción.

Gracias

**Comment by billthefarmer** [comment]
I had this happen again on a Samsung tablet with the Play Store version. Installing the latest version from [F-Droid](https://f-droid.org/en/packages/org.openintents.filemanager/) (2.2.3) fixed it.

**Comment by jormer1043** [comment]
Hice la instalación del F-Droid sin obtener un resultado favorable, comprobé los permisos de ambas aplicaciones y reinstalé el OI File Manager 2.3.1 pero aún así me sigue mostrando el error de acceso.
